# render.yaml

services:
  - type: web
    name: RiceSalinityPrediction  # Name of your web service
    env: python  # The environment for a Python app
    plan: free  # Specify the pricing plan: 'free' for free tier, or 'starter'/'standard' for paid tiers
    buildCommand: "pip install -r requirements.txt"  # Install dependencies using the requirements.txt file
    startCommand: "gunicorn app:app"  # Use Gunicorn to start the app, adjust as needed for your app's entry point

    # Optional environment variables
    envVars:
      - key: FLASK_ENV
        value: "production"
      - key: AZURE_CONNECTION_STRING
        sync: true  # Syncs the variable with Render's dashboard for added security
      - key: API_KEY
        sync: true

    # Specify the root directory of your project (if different from the repo root)
    rootDir: ./  # Adjust if your app is in a subfolder

    # Enable automatic deploys on pushes to the master/main branch
    autoDeploy: true

    # Optional: Set up automatic deployment previews for pull requests
    pullRequestPreviewsEnabled: true
    branch: main
